version: "3.8"
services:
  backend:
    image: "johnsantiago/springboot-react-fullstack:8.9.2021.22.46.48"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev