version: "3.8"
services:
  backend:
    image: "johnsantiago/springboot-react-fullstack:9.9.2021.18.37.25"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev